version: '2'
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: "typography"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "1"
    volumes:
      - ${PATH_TO_SQL}:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
